export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";

export const SIGN_IN_FAIL = "SIGN_IN_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const SET_TOTAL_DATA = "SET_TOTAL_DATA";
export const SET_DISBURSEMENT = "SET_DISBURSEMENT";
export const SET_REQUEST_MEMBER = "SET_REQUEST_MEMBER";
export const SET_REQUEST_ARTICLE = "SET_REQUEST_ARTICLE";
export const SET_ALL_ARTICLE = "SET_ALL_ARTICLE";
export const SET_ALL_USER = "SET_ALL_USER";
export const SET_ALL_FUND = "SET_ALL_FUND";
